webtalk_init -webtalk_dir C:/Users/Ponce/Desktop/finalAlfin/finalAlfin.sim/sim_1/behav/xsim/xsim.dir/MCD_MCM_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Feb  5 21:13:48 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "29814dfe-99e3-49f2-992d-1527061d7757" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "506dd8530f1d4ea69c1fd8bf4d96feb4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2008 R2 or Windows 7" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A6-4400M APU with Radeon(tm) HD Graphics   " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2695 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6380_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1278871575 -regid "" -xml C:/Users/Ponce/Desktop/finalAlfin/finalAlfin.sim/sim_1/behav/xsim/xsim.dir/MCD_MCM_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Ponce/Desktop/finalAlfin/finalAlfin.sim/sim_1/behav/xsim/xsim.dir/MCD_MCM_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Ponce/Desktop/finalAlfin/finalAlfin.sim/sim_1/behav/xsim/xsim.dir/MCD_MCM_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
